#creates the schema
CREATE SCHEMA `content_bowl` DEFAULT CHARACTER SET utf8 ;

#table tenant
CREATE TABLE `content_bowl`.`TENANT` (
  `ID_TENANT` INT NOT NULL,
  `DS_MNEMONIC` VARCHAR(45) NOT NULL,
  `DS_DESCRIPTION` VARCHAR(256) NOT NULL,
  `IS_ACTIVE` CHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`ID_TENANT`),
  UNIQUE INDEX `DS_MNEMONIC_UNIQUE` (`DS_MNEMONIC` ASC));

#table api_client
CREATE TABLE `content_bowl`.`API_CLIENT` (
  `ID_API_CLIENT` INT NOT NULL,
  `ID_TENANT` INT NOT NULL,
  `DS_API_KEY` VARCHAR(64) NOT NULL,
  `DS_DESCRIPTION` VARCHAR(256) NOT NULL,
  `IS_ACTIVE` CHAR(1) NOT NULL DEFAULT 'Y',
  `DT_EXPIRATION` DATETIME NULL,
  PRIMARY KEY (`ID_API_CLIENT`),
  UNIQUE INDEX `DS_API_KEY_UNIQUE` (`DS_API_KEY` ASC));

ALTER TABLE `content_bowl`.`API_CLIENT` 
	ADD INDEX `FK_TENANT_idx` (`ID_TENANT` ASC);
ALTER TABLE `content_bowl`.`API_CLIENT` 
	ADD CONSTRAINT `FK_TENANT`
	 	FOREIGN KEY (`ID_TENANT`)
	 	REFERENCES `content_bowl`.`TENANT` (`ID_TENANT`)
	 	ON DELETE NO ACTION
	 	ON UPDATE NO ACTION;

ALTER TABLE `content_bowl`.`API_CLIENT` 
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`ID_API_CLIENT`, `ID_TENANT`);

#table configuration_category
CREATE TABLE `content_bowl`.`CONFIGURATION_CATEGORY` (
  `ID_CONF_CATEGORY` INT NOT NULL,
  `DS_MNEMONIC` VARCHAR(64) NOT NULL,
  `DS_DESCRIPTION` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`ID_CONF_CATEGORY`),
  UNIQUE INDEX `DS_MNEMONIC_UNIQUE` (`DS_MNEMONIC` ASC));

#table configuration_attribute
CREATE TABLE `content_bowl`.`CONFIGURATION_ATTRIBUTE` (
  `ID_CONF_ATTRIBUTE` INT NOT NULL,
  `ID_CONF_CATEGORY` INT NOT NULL,
  `DS_MNEMONIC` VARCHAR(64) NOT NULL,
  `DS_DESCRIPTION` VARCHAR(256) NOT NULL,
  `DS_TYPE` CHAR(1) NOT NULL,
  `IS_MULTIVALUED` CHAR(1) NOT NULL DEFAULT 'N',
  `IS_REQUIRED` CHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ID_CONF_ATTRIBUTE`),
  UNIQUE INDEX `DS_MNEMONIC_UNIQUE` (`DS_MNEMONIC` ASC));

ALTER TABLE `content_bowl`.`CONFIGURATION_ATTRIBUTE` 
	ADD INDEX `FK_CATEGORY_idx` (`ID_CONF_CATEGORY` ASC);
ALTER TABLE `content_bowl`.`CONFIGURATION_ATTRIBUTE` 
	ADD CONSTRAINT `FK_CATEGORY`
  		FOREIGN KEY (`ID_CONF_CATEGORY`)
  		REFERENCES `content_bowl`.`CONFIGURATION_CATEGORY` (`ID_CONF_CATEGORY`)
  		ON DELETE NO ACTION
  		ON UPDATE NO ACTION;

#table configuration_value
CREATE TABLE `content_bowl`.`CONFIGURATION_VALUE` (
  `ID_CONF_ATTRIBUTE` INT NOT NULL,
  `ID_TENANT` INT NOT NULL,
  `DS_VALUE` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`ID_CONF_ATTRIBUTE`, `ID_TENANT`));

ALTER TABLE `content_bowl`.`CONFIGURATION_VALUE` 
	ADD INDEX `FK_CONF_VALUE_TENANT_idx` (`ID_TENANT` ASC);
ALTER TABLE `content_bowl`.`CONFIGURATION_VALUE` 
	ADD CONSTRAINT `FK_CONF_VALUE_TENANT`
  		FOREIGN KEY (`ID_TENANT`)
  		REFERENCES `content_bowl`.`TENANT` (`ID_TENANT`)
  		ON DELETE NO ACTION
  		ON UPDATE NO ACTION;

ALTER TABLE `content_bowl`.`CONFIGURATION_VALUE` 
ADD CONSTRAINT `FK_CONF_VALUE_ATTRIB`
  FOREIGN KEY (`ID_CONF_ATTRIBUTE`)
  REFERENCES `content_bowl`.`CONFIGURATION_ATTRIBUTE` (`ID_CONF_ATTRIBUTE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

